# Generated by Django 4.2.11 on 2024-06-20 16:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_blog_image_alter_blog_posted_alter_comment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attractions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='Текст комментария')),
                ('thematic_group', models.CharField(choices=[('extrim', 'Экстримальные аттракционы'), ('family', 'Семейные аттракционы'), ('child', 'Детские аттракционы')], max_length=100, verbose_name='Группа аттракционов')),
                ('price', models.FloatField()),
            ],
            options={
                'verbose_name': 'Аттракционы',
                'verbose_name_plural': 'Аттракционы',
                'db_table': 'Attractions',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.CharField(choices=[('adult', 'Взрослый'), ('child', 'Детский')], default='adult', max_length=100, verbose_name='Тип билета')),
                ('status', models.CharField(choices=[('standard', 'Standard'), ('vip', 'VIP'), ('platinum', 'Platinum')], default='standard', max_length=100, verbose_name='Статус билета')),
                ('attractions', models.CharField(choices=[('Детские', (('osminog', 'Осьминожка'), ('fire', 'Пожарная команда'), ('aviat', 'Авиаторы'))), ('Семейные', (('koleso', 'Колесо обозрения'), ('katam', 'Катамараны'), ('gonki', 'Крутые гонки'))), ('Экстримальные', (('katap', 'Катапульта'), ('shaker', 'Шейкер'), ('free', 'Свободное падение')))], default='Семейные', max_length=100, verbose_name='Аттракционы')),
                ('group', models.CharField(choices=[('extrim', 'Экстримальные аттракционы'), ('family', 'Семейные аттракционы'), ('child', 'Детские аттракционы')], default='family', max_length=100, verbose_name='Группа аттракционов')),
                ('count', models.IntegerField()),
                ('price', models.FloatField()),
                ('date', models.DateTimeField(db_index=True, default=datetime.datetime(2024, 6, 20, 19, 11, 37, 915107), verbose_name='Дата покупки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Купленные билеты',
                'verbose_name_plural': 'Купленные билеты',
                'db_table': 'Tickets',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-posted'], 'verbose_name': 'Статья блога', 'verbose_name_plural': 'Статьи блога'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 6, 20, 19, 11, 37, 914116), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 6, 20, 19, 11, 37, 914116), verbose_name='Дата комментария'),
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(db_index=True, default=datetime.datetime(2024, 6, 20, 19, 11, 37, 915107), verbose_name='Дата посещения')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.attractions', verbose_name='Аттракционы')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tickets', verbose_name='Билет')),
            ],
            options={
                'verbose_name': 'Посещения',
                'verbose_name_plural': 'Посещения',
                'db_table': 'Visits',
                'ordering': ['-date'],
            },
        ),
    ]
