# Generated by Django 5.0.6 on 2024-06-21 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_blog_posted_alter_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 6, 21, 16, 1, 50, 166425), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 6, 21, 16, 1, 50, 167423), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 6, 21, 16, 1, 50, 167423), verbose_name='Дата покупки'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='group',
            field=models.CharField(choices=[('extrim', 'Экстремальные аттракционы'), ('family', 'Семейные аттракционы'), ('child', 'Детские аттракционы')], default='family', max_length=100, verbose_name='Группа аттракционов'),
        ),
        migrations.AlterField(
            model_name='visits',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 6, 21, 16, 1, 50, 168420), verbose_name='Дата посещения'),
        ),
    ]
