# Generated by Django 5.0.6 on 2024-06-22 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_blog_posted_alter_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractions',
            name='name',
            field=models.TextField(max_length=100, verbose_name='Название аттракциона'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 6, 22, 22, 18, 10, 491678), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 6, 22, 22, 18, 10, 492700), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='attractions',
            field=models.CharField(choices=[('Детские', [('osminog', 'Осьминожка'), ('fire', 'Пожарная команда'), ('aviat', 'Авиаторы')]), ('Семейные', [('koleso', 'Колесо обозрения'), ('katam', 'Катамараны'), ('gonki', 'Крутые гонки')]), ('Экстремальные', [('katap', 'Катапульта'), ('shaker', 'Шейкер'), ('free', 'Свободное падение')])], default='Семейные', max_length=100, verbose_name='Аттракционы'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 6, 22, 22, 18, 10, 492700), verbose_name='Дата покупки'),
        ),
        migrations.AlterField(
            model_name='visits',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 6, 22, 22, 18, 10, 493697), verbose_name='Дата посещения'),
        ),
    ]
