# Generated by Django 5.0.6 on 2024-06-22 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_attractions_name_alter_blog_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 6, 22, 23, 3, 4, 461150), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 6, 22, 23, 3, 4, 461150), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='attractions',
            field=models.CharField(blank=True, choices=[('Детские', [('osminog', 'Осьминожка'), ('fire', 'Пожарная команда'), ('aviat', 'Авиаторы')]), ('Семейные', [('koleso', 'Колесо обозрения'), ('katam', 'Катамараны'), ('gonki', 'Крутые гонки')]), ('Экстремальные', [('katap', 'Катапульта'), ('shaker', 'Шейкер'), ('free', 'Свободное падение')])], max_length=100, null=True, verbose_name='Аттракционы'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 6, 22, 23, 3, 4, 462148), verbose_name='Дата покупки'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='group',
            field=models.CharField(blank=True, choices=[('extrim', 'Экстремальные аттракционы'), ('family', 'Семейные аттракционы'), ('child', 'Детские аттракционы')], max_length=100, null=True, verbose_name='Группа аттракционов'),
        ),
        migrations.AlterField(
            model_name='visits',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 6, 22, 23, 3, 4, 463145), verbose_name='Дата посещения'),
        ),
    ]
