# Generated by Django 5.0.6 on 2024-06-24 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_blog_posted_alter_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 6, 24, 20, 57, 38, 310994), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 6, 24, 20, 57, 38, 311991), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 6, 24, 20, 57, 38, 312990), verbose_name='Дата покупки'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='visits',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 6, 24, 20, 57, 38, 313986), verbose_name='Дата посещения'),
        ),
    ]
